defaults:
  - model: default
  - training: default
  - checkpoint: default
  - loss_weighting: default

mode: discrete
project_name: mix-token-bert
run_name: v0.1_discrete
log_model: all
logger: csv
data_dir: /Users/kurono/Documents/github/ContinuousMIDI/tmp/maestro_data_discrete
