defaults:
  - model: default
  - training: default
  - checkpoint: default
  - loss_weighting: default

project_name: mix-token-bert
run_name: v0.2
log_model: all
logger: wandb
data_dir: /kaggle/input/mstro-cont
